USE SDP;

DELETE FROM SQL_REGISTERS;

INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("APPLICATION ENCODING SCHEME", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("CLIENT_ACCTNG", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("CLIENT_APPLNAME", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("CLIENT_USERID", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("CLIENT_WRKSTNNAME", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("DATE", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("DEBUG MODE", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("DECFLOAT ROUNDING MODE", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("DEGREE", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("EXPLAIN MODE", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("GET_ACCEL_ARCHIVE", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("LC_CTYPE", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("MAINTAINED TYPES", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("MEMBER", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("OPTIMIZATION HINT", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("PACKAGE PATH", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("PACKAGESET", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("PATH", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("PRECISION", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("QUERY ACCELERATION", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("REFRESH AGE", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("ROUTINE VERSION", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("RULES", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("SCHEMA", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("SERVER", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("SQLID", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("TIME", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("TIME ZONE", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("ENCRYPTION PASSWORD", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("SESSION_USER", 0, 0)
INSERT INTO SQL_REGISTERS(name, peso, issue) VALUES ("USER", 0, 0)


COMMIT WORK;